CREATE DATABASE IF NOT EXISTS LP;
USE LP;

CREATE TABLE IF NOT EXISTS luckperms_users (
  id VARCHAR(36) PRIMARY KEY,
  uuid VARCHAR(36) UNIQUE,
  username VARCHAR(16),
  primary_group VARCHAR(36),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS luckperms_groups (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(36) UNIQUE,
  display_name VARCHAR(36),
  weight INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS luckperms_permissions (
  id VARCHAR(36) PRIMARY KEY,
  permission VARCHAR(255),
  value BOOLEAN DEFAULT TRUE,
  server VARCHAR(36),
  world VARCHAR(36),
  expiry TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  user_id VARCHAR(36),
  group_id VARCHAR(36),
  FOREIGN KEY (user_id) REFERENCES luckperms_users(id),
  FOREIGN KEY (group_id) REFERENCES luckperms_groups(id)
); 